# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bvarGroupPANEL <- function(S, Y, X, prior, starting_values, thin, show_progress, adptive_alpha_gamma, estimate_groups = FALSE) {
    .Call(`_bpvars_bvarGroupPANEL`, S, Y, X, prior, starting_values, thin, show_progress, adptive_alpha_gamma, estimate_groups)
}

bvarGroupPriorPANEL <- function(S, Y, X, prior, starting_values, thin, show_progress, adptive_alpha_gamma, estimate_groups = FALSE) {
    .Call(`_bpvars_bvarGroupPriorPANEL`, S, Y, X, prior, starting_values, thin, show_progress, adptive_alpha_gamma, estimate_groups)
}

bvarPANEL <- function(S, Y, missing, exogenous, prior, starting_values, thin, show_progress, adptive_alpha_gamma, type_wozniak, p) {
    .Call(`_bpvars_bvarPANEL`, S, Y, missing, exogenous, prior, starting_values, thin, show_progress, adptive_alpha_gamma, type_wozniak, p)
}

bvars_cpp <- function(S, Y, X, prior, starting_values, thin, show_progress, adptive_alpha_gamma, type_objective = FALSE) {
    .Call(`_bpvars_bvars_cpp`, S, Y, X, prior, starting_values, thin, show_progress, adptive_alpha_gamma, type_objective)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_bpvars_RcppExport_registerCCallable`)
})
